[package]
name = "cardamum"
description = "CLI to manage contacts"
version = "0.1.0"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["cli", "contact", "addressbook", "carddav", "webdav"]
homepage = "https://pimalaya.org/"
documentation = "https://github.com/pimalaya/cardamum/"
repository = "https://github.com/pimalaya/cardamum/"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

[dev-dependencies]
cardamum = { path = ".", features = [] }

[build-dependencies]
pimalaya-tui = { version = "0.2", default-features = false, features = ["build-envs"] }

[dependencies]
addressbook = { version = "0.1", features = [] }
addressbook-std = { version = "0.1", features = [] }
addressbook-std-native-tls = { version = "0.1", features = [] }
addressbook-std-rustls = { version = "0.1", features = [] }
clap = { version = "4.4", features = ["derive", "env", "wrap_help"] }
clap_complete = "4.4"
clap_mangen = "0.2"
color-eyre = "0.6"
comfy-table = "7.1"
crossterm = { version = "0.27", features = ["serde"] }
pimalaya-tui = { version = "0.2", default-features = false, features = ["cli", "config", "path", "tracing"] }
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
zeroize = "1"

[patch.crates-io]
addressbook-std-native-tls.git = "https://github.com/pimalaya/addressbook"
addressbook-std-rustls.git = "https://github.com/pimalaya/addressbook"
addressbook-std.git = "https://github.com/pimalaya/addressbook"
addressbook.git = "https://github.com/pimalaya/addressbook"
pimalaya-tui.git = "https://github.com/pimalaya/tui"
