[package]
name = "cardamum"
description = "CLI to manage contacts"
version = "0.1.0"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["cli", "contact", "addressbook", "carddav", "webdav"]
homepage = "https://pimalaya.org/"
documentation = "https://github.com/pimalaya/cardamum/"
repository = "https://github.com/pimalaya/cardamum/"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[features]
carddav = ["dep:addressbook-carddav", "addressbook/carddav"]
carddav-rustls = ["dep:addressbook-carddav-rustls", "addressbook/carddav"]
carddav-rustls-aws-lc = ["carddav-rustls", "addressbook-carddav-rustls/aws-lc"]
carddav-rustls-ring = ["carddav-rustls", "addressbook-carddav-rustls/ring"]
carddav-native-tls = ["dep:addressbook-carddav-native-tls", "addressbook/carddav"]
vendored = ["addressbook-carddav-native-tls?/vendored"]
full = ["carddav", "carddav-rustls-aws-lc", "carddav-rustls-ring", "carddav-native-tls"]

[build-dependencies]
pimalaya-tui = { version = "0.2", default-features = false, features = ["build-envs"] }

[dependencies]
addressbook = "0.1"
addressbook-carddav = { version = "0.1", default-features = false, optional = true }
addressbook-carddav-native-tls = { version = "0.1", default-features = false, optional = true }
addressbook-carddav-rustls = { version = "0.1", default-features = false, optional = true }
clap = { version = "4.4", features = ["derive", "env", "wrap_help"] }
clap_complete = "4.4"
clap_mangen = "0.2"
color-eyre = "0.6"
comfy-table = "7.1"
crossterm = { version = "0.27", features = ["serde"] }
pimalaya-tui = { version = "0.2", default-features = false, features = ["cli", "config", "path", "tracing"] }
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
zeroize = "1"

[patch.crates-io]
addressbook-carddav-native-tls.git = "https://github.com/pimalaya/addressbook"
addressbook-carddav-rustls.git = "https://github.com/pimalaya/addressbook"
addressbook-carddav.git = "https://github.com/pimalaya/addressbook"
addressbook.git = "https://github.com/pimalaya/addressbook"
pimalaya-tui.git = "https://github.com/pimalaya/tui"
