[package]
name = "cardamum"
description = "CLI to manage contacts"
version = "0.1.0"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["cli", "contact", "addressbook", "carddav", "webdav"]
homepage = "https://pimalaya.org/"
documentation = "https://github.com/pimalaya/cardamum/"
repository = "https://github.com/pimalaya/cardamum/"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []

[dev-dependencies]
cardamum = { path = ".", features = [] }

[dependencies]
base64 = { version = "0.22", features = [] }
chrono = { version = "0.4", features = [] }
memchr = { version = "2.7.4", features = [] }
quick-xml = { version = "0.37", features = ["serialize"] }
rustls = { version = "0.23", features = [] }
rustls-platform-verifier = { version = "0.5", features = [] }
serde = { version = "1", features = ["derive"] }
thiserror = { version = "2", features = [] }
