[package]
name = "cardamum"
description = "CLI to manage contacts"
version = "0.1.0"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["command-line-utilities"]
keywords = ["cli", "contact", "addressbook", "carddav", "webdav"]
homepage = "https://pimalaya.org"
documentation = "https://github.com/pimalaya/cardamum"
repository = "https://github.com/pimalaya/cardamum"

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["carddav", "rustls-aws-lc",  "native-tls", "command", "keyring"]

# CardDAV support without TLS (blocking)
#
carddav = ["dep:io-stream", "dep:http", "dep:secrecy", "io-addressbook/carddav"]

rustls = ["dep:rustls", "dep:rustls-platform-verifier"]
rustls-aws-lc = ["rustls/aws_lc_rs"]
rustls-ring = ["rustls/ring"]

native-tls = ["dep:native-tls"]

# Vdir support (blocking)
# See <https://vdirsyncer.pimutils.org/en/stable/vdir.html>
#
vdir = ["dep:io-fs", "io-addressbook/vdir"]

keyring = ["dep:io-keyring"]
command = ["dep:io-process"]

# Wizard to help you configure accounts interactively
# WIP: not ready, do not use!
#
# wizard = []

# Bring external libs to the build
#
vendored = ["native-tls?/vendored"]

[build-dependencies]
pimalaya-tui = { version = "0.2", default-features = false, features = ["build-envs"] }

[dependencies]
anyhow = "1"
clap = { version = "4.4", features = ["derive", "env", "wrap_help"] }
clap_complete = "4.4"
clap_mangen = "0.2"
comfy-table = "7.1"
crossterm = { version = "0.27", features = ["serde"] }
env_logger = "0.11"
http = { version = "1", optional = true }
io-addressbook = { version = "1", default-features = false }
io-fs = { version = "1", default-features = false, features = ["std"], optional = true }
io-keyring = { version = "1", default-features = false, features = ["serde", "std"], optional = true }
io-process = { version = "1", default-features = false, features = ["serde", "std"], optional = true }
io-stream = { version = "1", default-features = false, features = ["std"], optional = true }
log = "0.4"
native-tls = { version = "0.2", optional = true }
pimalaya-tui = { version = "0.2", default-features = false, features = ["cli", "config", "path"] }
rustls = { version = "0.23", default-features = false, features = ["logging", "std", "tls12"], optional = true }
rustls-platform-verifier = { version = "0.5", optional = true }
secrecy = { version = "0.10", features = ["serde"], optional = true }
serde = { version = "1", features = ["derive"] }

[patch.crates-io]
io-addressbook.path = "../addressbook"
io-fs.path = "../fs"
io-http.path = "../http"
io-keyring.path = "../keyring"
io-process.path = "../process"
io-stream.path = "../stream"
io-vdir.path = "../vdir"
pimalaya-tui.path = "../tui"
