[package]
name = "cardamum"
description = "CLI to manage contacts"
version = "0.2.0"
authors = ["Clément DOUIN (soywod) <clement.douin@posteo.net>"]
edition = "2024"
rust-version = "1.88"
license = "MIT OR Apache-2.0"
categories = ["command-line-utilities"]
keywords = ["cli", "contact", "carddav", "jmap", "vdir"]
homepage = "https://pimalaya.org"
repository = "https://github.com/pimalaya/cardamum"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["rustls-ring", "carddav", "jmap", "msgraph", "people", "pimdir", "vdir"]
carddav = ["dep:io-webdav", "dep:getrandom"]
jmap = ["dep:io-jmap", "dep:vcard-rs", "vcard-rs/jscontact", "dep:base64"]
msgraph = ["dep:io-msgraph", "dep:vcard-rs"]
people = ["dep:io-people", "dep:vcard-rs"]
pimdir = ["dep:io-pimdir", "dep:io-replica"]
vdir = ["dep:io-vdir"]
native-tls = ["pimalaya-stream/native-tls", "io-pim-discovery/native-tls", "io-webdav?/native-tls", "io-jmap?/native-tls", "io-msgraph?/native-tls", "io-people?/native-tls"]
rustls-aws = ["pimalaya-stream/rustls-aws", "io-pim-discovery/rustls-aws", "io-webdav?/rustls-aws", "io-jmap?/rustls-aws", "io-msgraph?/rustls-aws", "io-people?/rustls-aws"]
rustls-ring = ["pimalaya-stream/rustls-ring", "io-pim-discovery/rustls-ring", "io-webdav?/rustls-ring", "io-jmap?/rustls-ring", "io-msgraph?/rustls-ring", "io-people?/rustls-ring"]
vendored = ["pimalaya-stream/vendored", "io-webdav?/vendored", "io-jmap?/vendored", "io-msgraph?/vendored", "io-people?/vendored"]

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
panic = "abort"

[build-dependencies]
pimalaya-cli = { version = "0.2", default-features = false, features = ["build"] }

[dependencies]
anyhow = "1"
base64 = { version = "0.23", optional = true }
clap = { version = "4.4", features = ["derive", "env", "wrap_help"] }
clap_complete = "4.4"
clap_mangen = "0.3"
comfy-table = "8"
crossterm = { version = "0.29", default-features = false, features = ["serde"] }
dirs = "6"
env_logger = "0.11"
getrandom = { version = "0.4", optional = true }
io-http = { version = "0.3", default-features = false }
io-jmap = { version = "0.2", default-features = false, features = ["client"], optional = true }
io-msgraph = { version = "0.2", default-features = false, features = ["client"], optional = true }
io-people = { version = "0.2", default-features = false, features = ["client"], optional = true }
io-pim-discovery = { version = "0.5", default-features = false, features = ["pacc", "rfc6764", "rfc8620"] }
io-pimdir = { version = "0.2", default-features = false, features = ["client"], optional = true }
io-replica = { version = "0.3", default-features = false, optional = true }
io-vdir = { version = "0.1", default-features = false, features = ["client", "serde"], optional = true }
io-webdav = { version = "0.1", default-features = false, features = ["client"], optional = true }
log = "0.4"
percent-encoding = "2"
pimalaya-cli = { version = "0.2", default-features = false, features = ["carddav", "jmap", "prompt", "spinner", "table", "terminal", "wizard"] }
pimalaya-config = { version = "0.1", default-features = false, features = ["toml", "secret"] }
pimalaya-stream = { version = "0.1", default-features = false, features = ["std"] }
secrecy = "0.10"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
shellexpand = "3.1"
url = { version = "2.5", features = ["serde"] }
vcard-rs = { version = "0.2", default-features = false, features = ["parser"], optional = true }

[patch.crates-io]
io-msgraph.git = "https://github.com/pimalaya/io-msgraph"
io-people.git = "https://github.com/pimalaya/io-people"
io-vdir.git = "https://github.com/pimalaya/io-vdir"
io-pimdir.git = "https://github.com/pimalaya/io-pimdir"
io-replica.git = "https://github.com/pimalaya/io-replica"
io-webdav.git = "https://github.com/pimalaya/io-webdav"
pimalaya-cli.git = "https://github.com/pimalaya/cli"
vcard-rs.git = "https://github.com/pimalaya/vcard"
