################################################################
# Configuration examples                                       #
################################################################

[accounts.google]
carddav.discover.host = "www.googleapis.com"
carddav.discover.method = "PROPFIND"
carddav.server-uri = "https://www.googleapis.com/carddav/v1/principals"
carddav.home-uri = "https://www.googleapis.com/carddav/v1/principals/{{email}}/lists"
carddav.auth.bearer.command = ["ortie", "--account", "google", "token", "show"]

[accounts.icloud]
# there is no discovery domain for iCloud
carddav.server-uri = "https://contacts.icloud.com"
carddav.home-uri = "https://{{subdomain}}-contacts.icloud.com:443/{{id}}/carddavhome"
carddav.auth.basic.username = "{{email}}"
carddav.auth.basic.password.keyring = "cardamum-icloud"

[accounts.posteo]
carddav.discover.host = "posteo.de"
carddav.server-uri = "https://posteo.de:8843"
carddav.home-uri = "https://posteo.de:8843/addressbooks/{{username}}"
carddav.auth.basic.username = "{{username}}"
carddav.auth.basic.password.raw = "{{password}}"
