# The account name should be unique.
#
[accounts.example.carddav]

# Make this current account the default one to use when no account is
# specified in the CLI with the --account argument.
#
default = true
host = "127.0.0.1"
port = 8001
ssl = "plain"
auth = "plain"
home = "/user"
